module.exports = [
  {
    title: "Becoming",
    authors: ["Michelle Obama"],
    categories: [],
    description: "An intimate, powerful, and inspiring memoir by the former First Lady of the United States In a life filled with meaning and accomplishment, Michelle Obama has emerged as one of the most iconic and compelling women of our era. As First Lady of the United States of America—the first African American to serve in that role—she helped create the most welcoming and inclusive White House in history, while also establishing herself as a powerful advocate for women and girls in the U.S. and around the world, dramatically changing the ways that families pursue healthier and more active lives, and standing with her husband as he led America through some of its most harrowing moments. Along the way, she showed us a few dance moves, crushed Carpool Karaoke, and raised two down-to-earth daughters under an unforgiving media glare. In her memoir, a work of deep reflection and mesmerizing storytelling, Michelle Obama invites readers into her world, chronicling the experiences that have shaped her—from her childhood on the South Side of Chicago to her years as an executive balancing the demands of motherhood and work, to her time spent at the world’s most famous address. With unerring honesty and lively wit, she describes her triumphs and her disappointments, both public and private, telling her full story as she has lived it—in her own words and on her own terms. Warm, wise, and revelatory, Becoming is the deeply personal reckoning of a woman of soul and substance who has steadily defied expectations—and whose story inspires us to do the same.",
    img: "http://books.google.com/books/content?id=YbtNDwAAQBAJ&printsec=frontcover&img=1&zoom=2&edge=curl&imgtk=AFLRE70sFbLMWj8eXdZMyieQTIMyTLztJz42mX2JzrZWgudHNL7Q4nq0FfaEiJaQHvaD5h3n3jdhRBjLA4hm6Y7CjrT1f5CP1xhIU3aO0C7UI8jEd76tNFumoINFpCPPCv1n-l2rwCrf&source=gbs_api",
    price: 14.99,
    qty: 100
  }, {
    title: "Night Broken",
    authors: ["Patricia Briggs"],
    categories: ["Fiction / Fantasy / Contemporary", "Fiction / Fantasy / Urban"],
    description: `"#1 New York Times bestselling author Patricia Briggs's Mercy Thompson series has been hailed as "one of the best" (Fiction Vixen). Now, Mercy must deal with an unwanted guest-one that brings a threat unlike anything she's ever known. An unexpected phone call heralds a new challenge for Mercy. Her mate Adam's ex-wife is in trouble, on the run from a stalker. Adam isn't the kind of man to turn away a person in need-and Mercy knows it. But with Christy holed up in Adam's house, Mercy can't shake the feeling that something about the situation isn't right. Soon, her suspicions are confirmed when she learns that Christy has the farthest thing from good intentions. She wants Adam back and she's willing to do whatever it takes to make it happen, including turning Adam's pack against Mercy. Mercy isn't about to step down without a fight, but there's a more dangerous threat circling. Christy's stalker is more than a bad man-in fact, he may not be human at all. As the bodies start piling up, Mercy must put her personal troubles aside to face a creature with the power to tear her whole world apart."--`,
    img: "http://books.google.com/books/content?id=jzCKDQAAQBAJ&printsec=frontcover&img=1&zoom=2&edge=curl&imgtk=AFLRE72d3PJlWR9_lc3UAKO9ao2FQTuyPQkWaVc-DqWz6i4AlEvJT34qQekdaTQUaJ5X4KtJeOFR0aEDcbv4LH7I2GJJoB1vRQ_YzuQHv0CVFlCIBYF5mSJ5wto2oy5VDUxRaEGmLo-d&source=gbs_api",
    price: 0,
    qty: 0
  }, {
    title: "Educated",
    authors: ["Tara Westover"],
    categories: ["Biography & Autobiography / Women", "Biography & Autobiography / Religious", "Biography & Autobiography / Personal Memoirs"],
    description: "<b><b>#1 <i>NEW YORK TIMES, WALL STREET JOURNAL, </i>AND<i> BOSTON GLOBE </i>BESTSELLER • NAMED ONE OF THE TEN BEST BOOKS OF THE YEAR BY <i>THE NEW YORK TIMES BOOK REVIEW</i> • ONE OF PRESIDENT BARACK OBAMA’S FAVORITE BOOKS OF THE YEAR • BILL GATES<b>’S HOLIDAY READING LIST</b> • FINALIST FOR THE NATIONAL BOOK CRITICS CIRCLE’S JOHN LEONARD PRIZE FOR BEST FIRST BOOK • LONGLISTED FOR THE CARNEGIE MEDAL FOR EXCELLENCE <br><br>NAMED ONE OF THE BEST BOOKS OF THE YEAR BY <i>The Washington Post</i> •<i> O: The Oprah Magazine</i> • <i>Time</i> • NPR • <i>Good Morning America </i>• <i>San Francisco Chronicle</i> • <i>The Guardian </i>•<i> The Economist </i>• <i>Financial Times</i> • <i>Newsday</i> • <i>New York Post</i> • <i>theSkimm</i> • <i>Refinery29</i> • <i>Bloomberg</i> • <i>Self</i> • <i>Real Simple</i> •<i> Town & Country</i> • <i>Bustle</i> • <i>Paste</i> • <i>Publishers Weekly</i> • <i>Library Journal</i> • <i>LibraryReads</i> • <i>BookRiot</i> • Pamela Paul, KQED • New York Public Library</b><br><br><b>An unforgettable memoir about a young girl who, kept out of school, leaves her survivalist family and goes on to earn a PhD from Cambridge University</b><br></b><br>Born to survivalists in the mountains of Idaho, Tara Westover was seventeen the first time she set foot in a classroom. Her family was so isolated from mainstream society that there was no one to ensure the children received an education, and no one to intervene when one of Tara’s older brothers became violent. When another brother got himself into college, Tara decided to try a new kind of life. Her quest for knowledge transformed her, taking her over oceans and across continents, to Harvard and to Cambridge University. Only then would she wonder if she’d traveled too far, if there was still a way home.<br><b><br>“Beautiful and propulsive . . . Despite the singularity of [Tara Westover’s] childhood, the questions her book poses are universal: How much of ourselves should we give to those we love? And how much must we betray them to grow up?”—<i>Vogue</i></b><br><br><b>“Westover has somehow managed not only to capture her unsurpassably exceptional upbringing, but to make her current situation seem not so exceptional at all, and resonant for many others.”—<i>The New York Times Book Review</i></b>",
    img: "http://books.google.com/books/content?id=2ObWDgAAQBAJ&printsec=frontcover&img=1&zoom=2&edge=curl&imgtk=AFLRE71Nknhbtc6TaaeHMCLp-FNqbOB-uRHcnezTH9fQn9MEiu79vGKtkqoU-scut5TtePCgOOJ0hxgeZVcpE2ZhBqypsJr74h83H42vR1HMZoWupuJOqlSoZTPWlQotKDUYccgic5S3&source=gbs_api",
    price: 12.99,
    qty: 100
  }
]
